services:
    twig.extension.tangoman_front:
        class: TangoMan\FrontBundle\Twig\Extension\FrontExtension
        public: false
        arguments:
            - "@twig"
            - "@request_stack"
        tags:
            - { name: twig.extension }
